### ISSUE TITLE
crash on push

### ISSUE THREAD

**Issue by wanderer** [axic/mango#1]
I get this when I `push` a new branch
```
/usr/local/lib/node_modules/git-remote-mango/node_modules/bignumber.js/bignumber.js:1209
            throw error;
            ^

BigNumber Error: new BigNumber() not a base 16 number:
    at raise (/usr/local/lib/node_modules/git-remote-mango/node_modules/bignumber.js/bignumber.js:1177:25)
    at /usr/local/lib/node_modules/git-remote-mango/node_modules/bignumber.js/bignumber.js:1165:33
    at new BigNumber (/usr/local/lib/node_modules/git-remote-mango/node_modules/bignumber.js/bignumber.js:212:28)
    at SolidityTypeString.formatOutputString [as _outputFormatter] (/usr/local/lib/node_modules/git-remote-mango/node_modules/web3/lib/solidity/formatters.js:217:19)
    at /usr/local/lib/node_modules/git-remote-mango/node_modules/web3/lib/solidity/type.js:237:25
    at SolidityTypeString.SolidityType.decode (/usr/local/lib/node_modules/git-remote-mango/node_modules/web3/lib/solidity/type.js:238:11)
    at /usr/local/lib/node_modules/git-remote-mango/node_modules/web3/lib/solidity/coder.js:219:29
    at Array.map (native)
    at SolidityCoder.decodeParams (/usr/local/lib/node_modules/git-remote-mango/node_modules/web3/lib/solidity/coder.js:218:26)
    at SolidityFunction.unpackOutput (/usr/local/lib/node_modules/git-remote-mango/node_modules/web3/lib/web3/function.js:90:24)

To mango://0x351765a6e711cbd86de7f2a8442c857ae095d7ad
 * [new branch]      master -> master
error: failed to push some refs to 'mango://0x351765a6e711cbd86de7f2a8442c857ae095d7ad'
```

**Comment by wanderer** [comment]
The issue was caused by switching from testRPC to geth. I needed to recreate the contract

**Comment by axic** [comment]
It needs better error handling in that case.  Can you raise that as a specific issue on https://github.com/axic/git-remote-mango ?
